### PR TITLE
Optimize encoders and skip nul fields

### LINKED ISSUE #4: Support other libraries
Some libraries we might want to support:

- [ ] enumeratum
- [ ] cats datatypes, like `NonEmptyList` etc
- [ ] refined

### LINKED ISSUE #246: Option encoding behavior causing problems with GlobalSecondaryIndizes
First of all: Thank you for the excellent library. We (Autoscout24, hi from Munich) needed to switch from Scanamo, b/c we needed access to some low level operations and this made it really easy.

We discovered however a potential bug:

If a field is part of a Global Secondary Index key-set the `nul` AttributeValue [cannot be put into this field](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/dynamodb/model/PutItemRequest.html)
  
It causes troubles with the way Option[A] is encoded by default, because DynamoDB will fail with something like:

> One or more parameter values were invalid: Type mismatch for Index Key myNullableKey Expected: S Actual: NULL IndexName: MyGSI

This is the implementation in the library
```
  implicit def optionEncoder[A: ScynamoEncoder]: ScynamoEncoder[Option[A]] = {
    case Some(value) => ScynamoEncoder[A].encode(value)
    case None        => Right(AttributeValue.builder().nul(true).build())
  }
```

I changed it to:

```
  implicit def optionEncoder[A: ScynamoEncoder]: ScynamoEncoder[Option[A]] = {
    case Some(value) => ScynamoEncoder[A].encode(value)
    case None        => Right(null)
  }
```

This however changes the semantics, because in this case the Attribute will not be in DynamoDB at all. I'd argue this even might be desirable because it reduces costs for sparse data sets. What do you think about changing the default behavior in the library?

### PR DESCRIPTION
**Pull request by joroKr21**
Also add `Contravariant` instances (enable use of `narrow`)

Sorry for the big PR 🙈 
Fixes #246

### CODE REVIEW

File: src/main/scala/scynamo/ScynamoEncoder.scala [hunk 1]
```diff
@@ -12,119 +12,150 @@ import shapeless.tag.@@
...
-  def contramap[B](f: B => A): ScynamoEncoder[B] = value => self.encode(f(value))
+  def contramap[B](f: B => A): ScynamoEncoder[B] =
+    ScynamoEncoder.instance(value => self.encode(f(value)))
 }
 
 object ScynamoEncoder extends DefaultScynamoEncoderInstances {
   def apply[A](implicit instance: ScynamoEncoder[A]): ScynamoEncoder[A] = instance
+
+  // SAM syntax generates anonymous classes because of non-abstract methods like `contramap`.
+  private[scynamo] def instance[A](f: A => EitherNec[ScynamoEncodeError, AttributeValue]): ScynamoEncoder[A] = f(_)
```
Comment (markus1189) [inline src/main/scala/scynamo/ScynamoEncoder.scala:30]: I assume you wanted to move this, in order to avoid the generation of anonymous classes every time?  I'm not sure what exactly this `instance` method changes... :thinking:

File: src/main/scala/scynamo/ScynamoEncoder.scala [hunk 2]
```diff
@@ -12,119 +12,150 @@ import shapeless.tag.@@
...
+
+  // Ignore `nul` for efficiency and GSI support.
```
Comment (markus1189) [inline src/main/scala/scynamo/ScynamoEncoder.scala:32]: could we expand `GSI` to `Global Secondary Index`?  Not sure if the comment here really helps, maybe adding a dedicated test with a link to the issue would be better to know what invariant we want to ensure?

File: src/main/scala/scynamo/ScynamoEncoder.scala [hunk 3]
```diff
@@ -12,119 +12,150 @@ import shapeless.tag.@@
...
+  private[scynamo] def attributes(kvs: IndexedSeq[(String, AttributeValue)]) = {
```
Comment (markus1189) [inline src/main/scala/scynamo/ScynamoEncoder.scala:33]: Why `IndexedSeq`? I think we can use a more general type here?

File: src/main/scala/scynamo/ScynamoEncoder.scala [hunk 4]
```diff
@@ -12,119 +12,150 @@ import shapeless.tag.@@
...
+    }
 
   implicit def listEncoder[A: ScynamoEncoder]: ScynamoEncoder[List[A]] =
-    value =>
-      value.zipWithIndex
-        .parTraverse { case (x, i) =>
-          ScynamoEncoder[A].encode(x).leftMap(_.map(_.push(Index(i))))
-        }
-        .map(xs => AttributeValue.builder().l(xs: _*).build())
+    seqEncoder[A].narrow
```
Comment (markus1189) [inline src/main/scala/scynamo/ScynamoEncoder.scala:96]: this is beautiful :heart:

File: src/main/scala/scynamo/ScynamoEncoder.scala [hunk 5]
```diff
@@ -12,119 +12,150 @@ import shapeless.tag.@@
...
+      case Some(value) => element.encode(value)
+      case None        => rightNul
+    }
 
-  implicit def someEncoder[A: ScynamoEncoder]: ScynamoEncoder[Some[A]] = x => ScynamoEncoder[A].encode(x.get)
+  implicit def someEncoder[A](implicit element: ScynamoEncoder[A]): ScynamoEncoder[Some[A]] =
+    ScynamoEncoder.instance(some => element.encode(some.get))
 
-  implicit val finiteDurationEncoder: ScynamoEncoder[FiniteDuration] = longEncoder.contramap(_.toNanos)
+  implicit val finiteDurationEncoder: ScynamoEncoder[FiniteDuration] =
```
Comment (markus1189) [inline src/main/scala/scynamo/ScynamoEncoder.scala:113]: This is a breaking change I think :warning: .  Before this, we saved FiniteDuration as type Long, now it would be of type String in Dynamo.

File: src/main/scala/scynamo/ScynamoEncoder.scala [hunk 6]
```diff
@@ -12,119 +12,150 @@ import shapeless.tag.@@
...
+    numberStringEncoder.contramap(_.toNanos.toString)
 
-  implicit val durationEncoder: ScynamoEncoder[Duration] = longEncoder.contramap(_.toNanos)
+  implicit val durationEncoder: ScynamoEncoder[Duration] =
```
Comment (markus1189) [inline src/main/scala/scynamo/ScynamoEncoder.scala:116]: Same here, switches encoding from Long to String

Comment (markus1189) [reply src/main/scala/scynamo/ScynamoEncoder.scala:116]: I wonder if there was no test, if not we should add one

File: src/main/scala/scynamo/ScynamoEncoder.scala [hunk 7]
```diff
@@ -12,119 +12,150 @@ import shapeless.tag.@@
...
-          _.foldLeft(new java.util.HashMap[String, AttributeValue]()) { case (acc, (k, v)) =>
-            acc.put(k, v)
-            acc
-          }
+  implicit def mapEncoder[A, B](implicit key: ScynamoKeyEncoder[A], value: ScynamoEncoder[B]): ScynamoEncoder[Map[A, B]] =
+    ScynamoEncoder.instance { kvs =>
+      var allErrors  = Chain.empty[ScynamoEncodeError]
+      val attrValues = new java.util.HashMap[String, AttributeValue](kvs.size)
+      kvs.foreachEntry { (k, v) =>
+        (key.encode(k), value.encode(v)).parTupled match {
```
Comment (markus1189) [inline src/main/scala/scynamo/ScynamoEncoder.scala:124]: If we go for efficiency, we should probably remove the `parTupled` here as well and just pattern match all the cases

**Review by markus1189 — CHANGES_REQUESTED** [review]
That's a fast turnaround time for #246 @joroKr21 :heart: .  I had a look and added some comments.

Most importantly, I would like to have a dedicated test with a link to #246, to document it explicitly

File: src/main/scala/scynamo/ScynamoEncoder.scala (hunk 1 above)
Comment (joroKr21) [reply src/main/scala/scynamo/ScynamoEncoder.scala:30]: The best way to check is to clean compile before the change and after the change - you should see a bunch of anon classes disappear 😬 - it's really a bug in the Scala compiler that can't be fixed without breaking binary compatibility.

File: src/main/scala/scynamo/ScynamoEncoder.scala (hunk 5 above)
Comment (joroKr21) [reply src/main/scala/scynamo/ScynamoEncoder.scala:113]: `longEncoder` is just `numberStringEncoder.contramap(_.toString)`

File: src/main/scala/scynamo/ScynamoEncoder.scala (hunk 6 above)
Comment (joroKr21) [reply src/main/scala/scynamo/ScynamoEncoder.scala:116]: Same reason - we definitely need more tests but this particular change is covered by the golden test

File: src/main/scala/scynamo/ScynamoEncoder.scala (hunk 7 above)
Comment (joroKr21) [reply src/main/scala/scynamo/ScynamoEncoder.scala:124]: Probably 👍

File: src/main/scala/scynamo/ScynamoEncoder.scala (hunk 3 above)
Comment (joroKr21) [reply src/main/scala/scynamo/ScynamoEncoder.scala:33]: This is unused now - I will remove it

File: src/main/scala/scynamo/ScynamoEncoder.scala (hunk 1 above)
Comment (markus1189) [reply src/main/scala/scynamo/ScynamoEncoder.scala:30]: Well TIL :+1:

File: src/main/scala/scynamo/ScynamoEncoder.scala (hunk 5 above)
Comment (markus1189) [reply src/main/scala/scynamo/ScynamoEncoder.scala:113]: Oh okay nevermind then ;)

**Review by saeltz — COMMENTED** [review]
Awesome!

File: src/main/scala/scynamo/ScynamoEncoder.scala [hunk 8]
```diff
@@ -12,119 +12,150 @@ import shapeless.tag.@@
...
+  private[scynamo] def attributes(kvs: IndexedSeq[(String, AttributeValue)]) = {
+    val attr = new java.util.HashMap[String, AttributeValue](kvs.size)
+    for ((k, v) <- kvs) if (!v.nul) attr.put(k, v)
+    attr
+  }
 }
 
 trait DefaultScynamoEncoderInstances extends ScynamoIterableEncoder {
-  implicit val stringEncoder: ScynamoEncoder[String] = value => Right(AttributeValue.builder().s(value).build())
+  private val rightNul = Right(AttributeValue.builder.nul(true).build())
```
[the remark this answers is not in the document]
Comment (joroKr21) [reply src/main/scala/scynamo/ScynamoEncoder.scala:41]: Private values are effectively final

File: src/main/scala/scynamo/ScynamoDecoder.scala [hunk 9]
```diff
@@ -40,6 +40,18 @@ object StackFrame {
...
+      encoded: EitherNec[ScynamoEncodeError, A],
+      frame: StackFrame
+  ): EitherNec[ScynamoEncodeError, A] =
+    encoded.leftMap(encoding(_, frame))
+
+  private[scynamo] def encoding[A](
+      errors: NonEmptyChain[ScynamoEncodeError],
+      frame: StackFrame
+  ): NonEmptyChain[ScynamoEncodeError] =
+    errors.map(_.push(frame))
```
[the remark this answers is not in the document]
Comment (joroKr21) [reply src/main/scala/scynamo/ScynamoDecoder.scala:54]: I don't know it's used also in `ShapelessScynamoEncoder`

[the remark this answers is not in the document]
Comment (saeltz) [reply src/main/scala/scynamo/ScynamoDecoder.scala:54]: Still I wouldn't expect encoders in the decoder file.

[the remark this answers is not in the document]
Comment (joroKr21) [reply src/main/scala/scynamo/ScynamoDecoder.scala:54]: I don't why `StackFrame` is in this file - I guess I could take it out - it's used by both

**Review by saeltz — APPROVED** [review]
Thanks for adding the tests as well!

**Review by markus1189 — APPROVED** [review]

File: src/main/scala/scynamo/ScynamoEncoder.scala [hunk 10]
```diff
@@ -12,119 +12,151 @@ import shapeless.tag.@@
...
+import scala.collection.immutable.Seq
 import scala.concurrent.duration.{Duration, FiniteDuration}
-import scala.jdk.CollectionConverters._
 
 trait ScynamoEncoder[A] { self =>
   def encode(value: A): EitherNec[ScynamoEncodeError, AttributeValue]
-
-  def contramap[B](f: B => A): ScynamoEncoder[B] = value => self.encode(f(value))
+  def contramap[B](f: B => A): ScynamoEncoder[B] =
+    ScynamoEncoder.instance(value => self.encode(f(value)))
```
[the remark this answers is not in the document]
Comment (joroKr21) [reply src/main/scala/scynamo/ScynamoEncoder.scala:23]: Yes - I find it hard to read such long lines without a break
